# Generated by Django 5.0 on 2024-01-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=255)),
                ('description_arabic', models.TextField()),
                ('name_english', models.CharField(max_length=255)),
                ('description_english', models.TextField()),
            ],
            options={
                'verbose_name': 'سلعة',
                'verbose_name_plural': 'عناصر',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_photos', verbose_name='')),
                ('itemf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
