# Generated by Django 5.0 on 2024-01-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_itemimage_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'صورة السلعة', 'verbose_name_plural': 'صور السلع'},
        ),
        migrations.AddField(
            model_name='item',
            name='small_photo',
            field=models.ImageField(blank=True, null=True, upload_to='small_photos', verbose_name='الصورة المصغرة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_arabic',
            field=models.TextField(verbose_name='التفاصيل بالعربي'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_english',
            field=models.TextField(verbose_name='التفاصيل بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_arabic',
            field=models.CharField(max_length=255, verbose_name='العنوان بالعربي'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_english',
            field=models.CharField(max_length=255, verbose_name='العنوان بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='item_photos', verbose_name='صورة للسلعة'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='itemf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='السلعة'),
        ),
    ]
