# Generated by Django 5.0 on 2024-01-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('what_it_do', models.CharField(max_length=255)),
                ('screenshottoit', models.ImageField(upload_to='web_screen')),
                ('arabic_transulate', models.TextField()),
                ('english_trans', models.TextField()),
                ('pk_for_this_obj', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '-',
                'verbose_name_plural': 'تعديل على الموقع',
            },
        ),
    ]
